data1 <- read.table("./household_power_consumption.txt", stringsAsFactors = FALSE, header = TRUE, sep =";" )
Full<- strptime(paste(data1$Date, data1$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
data1 <- cbind(data1, Full)
data1$Date <- as.Date(data1$Date, format="%d/%m/%Y")
data1$Time <- format(data1$Time, format="%H:%M:%S")
data1$Sub_metering_1 <- as.numeric(data1$Sub_metering_1)
data1$Sub_metering_2 <- as.numeric(data1$Sub_metering_2)
data1$Sub_metering_3 <- as.numeric(data1$Sub_metering_3)
data1$Global_active_power <- as.numeric(powerdata$Global_active_power)
subsetdata <- subset(data1, Date == "2007-02-01" | Date =="2007-02-02")
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
with(subsetdata, plot(Full, Global_active_power, type="l", xlab="", ylab="Global Active Power"))
with(subsetdata, plot(Full, Voltage, type = "l", xlab="datetime", ylab="Voltage"))
with(subsetdata, plot(Full, Sub_metering_1, type="l", xlab="", ylab="Energy sub metering"))
lines(subsetdata$Full, subsetdata$Sub_metering_2,type="l", col= "red")
lines(subsetdata$Full, subsetdata$Sub_metering_3,type="l", col= "blue")
with(subsetdata, plot(Full, Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power"))
dev.off()
