data1 <- read.table("./household_power_consumption.txt", stringsAsFactors = FALSE, header = TRUE, sep =";" )
Full<- strptime(paste(data1$Date, data1$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
data1 <- cbind(data1, Full)
data1$Date <- as.Date(data1$Date, format="%d/%m/%Y")
data1$Time <- format(data1$Time, format="%H:%M:%S")
data1$Sub_metering_1 <- as.numeric(data1$Sub_metering_1)
data1$Sub_metering_2 <- as.numeric(data1$Sub_metering_2)
data1$Sub_metering_3 <- as.numeric(data1$Sub_metering_3)
subsetdata <- subset(data1, Date == "2007-02-01" | Date =="2007-02-02")
png("plot3.png", width=480, height=480)
with(subsetdata, plot(Full, Sub_metering_1, type="l", xlab="Day", ylab="Global Active Power"))
lines(subsetdata$Full, subsetdata$Sub_metering_2,type="l", col= "red")
lines(subsetdata$Full, subsetdata$Sub_metering_3,type="l", col= "blue")
dev.off()
