data1 <- read.table("./household_power_consumption.txt", stringsAsFactors = FALSE, header = TRUE, sep =";" )
Full<- strptime(paste(data1$Date, data1$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
data1 <- cbind(data1, Full)
data1$Date <- as.Date(data1$Date, format="%d/%m/%Y")
data1$Time <- format(data1$Time, format="%H:%M:%S")
data1$Global_active_power <- as.numeric(data1$Global_active_power)
subsetdata <- subset(data1, Date == "2007-02-01" | Date =="2007-02-02")
png("plot2.png", width=480, height=480)
with(subsetdata, plot(Full, Global_active_power, xlab="Day", ylab="Global Active Power"))
dev.off()